service: inwardapi

plugins:
  - serverless-latest-layer-version

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:us-east-1:836509539324:table/TestResolver

    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - arn:aws:sns:us-east-1:836509539324:TestingSNSTopic
functions:
  testFunction:
    handler: handler.testFunction
    description: invoke the test function from the inwardApi
    events:
      - http:
          path: testFunction
          method: get
      # - sns: TestSNSTopic  
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:836509539324:layer:shared-dependencies:latest
  
  testingFunction:
    handler: handler.testingFunction
    description: invoke this function from SNS topic
    events:
      - sns: TestingSNSTopic
    environment:
      NODE_PATH: "./:/opt/node_modules"
    layers:
      - arn:aws:lambda:us-east-1:836509539324:layer:shared-dependencies:latest

#   mockAuthorizer:
#     handler: handler.mockAuthorizer

resources:
  Resources:
    SNSTopic:
      Type: 'AWS::SNS::Topic'
      Properties:
        DisplayName: TestSNSTopic